Feat/collection
shoedler/tabletop-gather pull request #32
Opened 2023-12-02 16:31 UTC by Raemy92

Adds User Collection and Add to collection Components

TODOs:
- [ ] Get games from API
- [ ] Add games using API
- [ ] remove weird margins between search field and game cards
- [ ] Unit Tests for GameService

2023-12-06 19:25 UTC, shoedler requested changes
Ha eifach z Frontend aagluegt

2023-12-06 19:25 UTC, shoedler commented on apps/frontend/src/styles.scss
> +.tg-flex-grow-1 {
I ha die äxtra so wie Tailwind gmacht:
![image](https://github.com/shoedler/tabletop-gather/assets/38029550/a03f5fa8-7407-4625-92d2-4d3298800d39)
La doch die so ;)

2023-12-06 19:25 UTC, shoedler commented on apps/frontend/src/app/components/atoms/input.component.ts
> +    <nb-form-field>
Chöimer da bitte ä *search-input.component.ts* mache?
So het jede Input no z ganze Formsmodule drinne.

2023-12-06 19:25 UTC, shoedler commented on apps/frontend/src/app/components/molecules/collection-actions.component.ts
> +  @Output() private searchInput = new EventEmitter<string>();
Würd da `searchTerm` nä

2023-12-06 19:25 UTC, shoedler commented on apps/frontend/src/app/components/organisms/view-collection-own.component.ts
> +    private readonly gameService: GameService
Bitte nid dr `gameService` hie drinne resolve - mach doch das ir Page und due hie ä  `@Output deleteMyGame = new EventEmitter<Game>();` dri. De heimers überall glych :)
I ha jewils d Domain Services (user*, gathering*, planService usw. ) nur ide page components resolved.

2023-12-06 19:25 UTC, shoedler commented on apps/frontend/src/app/components/pages/add-to-collection.component.ts
> +  @HostListener('window:scroll', ['$event'])
Dekorierti methode würdi immer zoberst - o wesi private sy ;)

2023-12-06 19:25 UTC, shoedler commented on apps/frontend/src/app/components/pages/collection.component.ts
> +    this.loadGames();
Mach ds doch im onInit, dä Call geit ja äue ewig. Am beste sogar als Promise

2023-12-06 19:25 UTC, shoedler commented on apps/frontend/src/app/services/game.service.ts
> +      .get<object>(this.gamesUrl, {
```suggestion
      .get<{ content: object[] }>(this.gamesUrl, {
```
De chames unger im `response?.body as ...` lösche :)

2023-12-07 07:00 UTC, Raemy92 commented on apps/frontend/src/app/components/atoms/input.component.ts
> +    <nb-form-field>
Auso inputComponent zrugbue wis gsih isch u as komplett nüüs searchComponent oder wie minsch?

2023-12-07 17:40 UTC, shoedler commented on apps/frontend/src/app/components/atoms/input.component.ts
> +    <nb-form-field>
Ja, dä code wod jetz hesc im inputcomponent kopiere ine nöie "search-input" und när dr input wider reverte ;)

2023-12-07 21:33 UTC, Raemy92 commented on apps/frontend/src/styles.scss
> +.tg-flex-grow-1 {
Done

2023-12-07 21:33 UTC, Raemy92 commented on apps/frontend/src/app/components/atoms/input.component.ts
> +    <nb-form-field>
Done

2023-12-07 21:33 UTC, Raemy92 commented on apps/frontend/src/app/components/molecules/collection-actions.component.ts
> +  @Output() private searchInput = new EventEmitter<string>();
Done

2023-12-07 21:33 UTC, Raemy92 commented on apps/frontend/src/app/components/organisms/view-collection-own.component.ts
> +    private readonly gameService: GameService
Done

2023-12-07 21:33 UTC, Raemy92 commented on apps/frontend/src/app/components/pages/collection.component.ts
> +    this.loadGames();
Done

2023-12-07 21:33 UTC, Raemy92 commented on apps/frontend/src/app/services/game.service.ts
> +      .get<object>(this.gamesUrl, {
Done

2023-12-09 15:04 UTC, shoedler requested changes
Heisser Scheiss!

Ha no 2 chlyni Sache kommentiert.

---

När hani hie no ä Branch gmacht https://github.com/shoedler/tabletop-gather/tree/feat/collection-style

Zum dr Style aligne. Links alt, rechts neu:
![image](https://github.com/shoedler/tabletop-gather/assets/38029550/c54285bd-4066-4e12-980a-ba85a847e5ae)
@yungxramoz bitte ono churz prüefe

2023-12-09 19:25 UTC, Raemy92 commented on apps/frontend/src/app/app.component.ts
> +          (click)="navigateBackIfApplicable()"
würd umi reverted -> gfüne da sicher a schlaueri lösig :)

2023-12-09 19:27 UTC, Raemy92 commented on apps/frontend/src/app/components/pages/collection.component.ts
>    protected isLoading = false;
boah i tubu... :D

2023-12-10 01:41 UTC, shoedler approved these changes

2023-12-10 01:41 UTC, merged